FROM python:3.10-slim

WORKDIR /app

RUN apt-get update  \
    && apt-get install -y gcc=4:12.2.0-3 --no-install-recommends  \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir uwsgi==2.0.21

COPY ./src ./uwsgi.ini ./

CMD ["uwsgi", "--ini", "uwsgi.ini"]
