services:
  proxy:
    image: "nginx:1.27-alpine"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    restart: always
    depends_on: [uwsgi, gunicorn]
    ports:
      - "8080:80"
      - "8081:81"
  uwsgi:
    image: "uwsgi"
    build:
      context: .
      dockerfile: Dockerfile.uwsgi
    restart: always
  gunicorn:
    image: gunicorn
    build:
      context: .
      dockerfile: Dockerfile.gunicorn
    restart: always
    environment:
      PYTHONUNBUFFERED: TRUE  # disable the Python stdout buffering
