FROM python:3.10-slim-buster

WORKDIR /app

RUN apt-get update  \
    && apt-get install -y build-essential --no-install-recommends  \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir uwsgi

COPY ./src ./uwsgi.ini ./

CMD ["uwsgi", "--ini", "uwsgi.ini"]
