services:
  proxy:
    image: "nginx:1.27-alpine"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "static-volume:/public/static:ro"
    depends_on:
      gunicorn:
        condition: service_started
    restart: always
    ports:
      - "8080:80"
  init-backend:
    build:
      context: .
      dockerfile: Dockerfile.gunicorn
    volumes:
      - "./src:/app"
      - "./gunicorn.conf.py:/gunicorn.conf.py"
      - "./init.sh:/init.sh"
      - "static-volume:/app/static"
    command: /init.sh
  gunicorn:
    image: gunicorn
    build:
      context: .
      dockerfile: Dockerfile.gunicorn
    volumes:
      - "./src:/app"
      - "./gunicorn.conf.py:/gunicorn.conf.py"
      - "static-volume:/app/static"
    depends_on:
      init-backend:
        condition: service_completed_successfully
    restart: always
    environment:
      PYTHONUNBUFFERED: TRUE  # disable the Python stdout buffering

volumes:
  static-volume:
