version: "3.9"

services:
  proxy:
    image: nginx:1.25
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "static-volume:/public/static:ro"
    depends_on: [gunicorn]
    restart: always
    ports:
      - "8080:80"
  gunicorn:
    image: gunicorn
    build:
      context: .
      dockerfile: Dockerfile.gunicorn
    volumes:
      - "./src:/app"
      - "./gunicorn.conf.py:/gunicorn.conf.py"
      - "static-volume:/app/static"
    restart: always
    environment:
      PYTHONUNBUFFERED: TRUE  # disable the Python stdout buffering

volumes:
  static-volume:
