FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir gunicorn==20.1.0

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./gunicorn.conf.py /
COPY ./src ./

CMD ["gunicorn", "-c", "/gunicorn.conf.py"]
